#server:
#  port: 8764
#  servlet:
#    context-path: /neo4j-jdbc

spring:
  application:
    name: neo4j-jdbc
  servlet:
    multipart:
      #springboot 2.1 后增加 DataSize ,用来避免数据曝光
      max-file-size: 104857600
      max-request-size: 524288000
  datasource:
    url: jdbc:mysql://10.0.46.130:43306/bmsmartkg_v13?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
    username: admin
    password: Bmzt2016_mysql
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 10
    maxIdle: 15
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 5
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    config:
      name: neo4j-jdbc
      profile: dev

#存储相关配置
storage:
  neo4j:
    url: bolt://10.0.46.53:7687
    userName: neo4j
    password: root