server:
  port: 8764
  servlet:
    context-path: /neo4j-jdbc

spring:
  application:
    name: neo4j-jdbc
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  servlet:
    multipart:
      #springboot 2.1 后增加 DataSize ,用来避免数据曝光
      max-file-size: 104857600
      max-request-size: 524288000
  security:
    user:
      name: admin
      password: admin

#存储相关配置
storage:
  neo4j:
    url: bolt://localhost:11005
    userName: neo4j
    password: 123456


eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/

#日志配置
logging:
  level:
    root: info
