server:
  port: 8764

spring:
  application:
    name: neo4j-jdbc

eureka:
  client:
    service-url: http://localhost:8761/eureka/
  # 这只为prefer ip的话可以直接展示ip地址
  instance:
    prefer-ip-address: true