server:
  port: 8768
  servlet:
    context-path: /wikl-component

spring:
  application:
    name: wikl-component
  servlet:
    multipart:
      #springboot 2.1 后增加 DataSize ,用来避免数据曝光
      max-file-size: 104857600
      max-request-size: 524288000

eureka:
  client:
    service-url: http://localhost:8761/eureka/
  # 这只为prefer ip的话可以直接展示ip地址
  instance:
    prefer-ip-address: true

# 日志配置
#logging:
#  level: debug
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"