server:
  port: 8769
  servlet:
    context-path: /orientdb-spark

spring:
  application:
    name: orientdb-spark

eureka:
  client:
    service-url: http://localhost:8761/eureka/
  # 这只为prefer ip的话可以直接展示ip地址
  instance:
    prefer-ip-address: true